/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.trabajador;

import conexion.ConexionBBDD;
import gui.internal.nuevo.InternalNuevaFinca;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author David López González
 */
public class NuevoGastoManoObra extends javax.swing.JFrame
{

    JTable jtbGastoManoObra;
    int id;
    boolean modificar = false;
    String DNI;

    public NuevoGastoManoObra()
    {
        initComponents();
    }

    public NuevoGastoManoObra(JTable jtbGastoManoObra,String DNI)
    {
        initComponents();
        modificar = false;
        this.DNI=DNI;
        this.jtbGastoManoObra = jtbGastoManoObra;
    }

    public NuevoGastoManoObra(JTable jtbGastoManoObra, int id,String DNI) throws Exception
    {
        initComponents();
        this.id = id;
        this.jtbGastoManoObra = jtbGastoManoObra;
        this.DNI=DNI;
        modificar = true;
        rellenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dateInicio = new com.toedter.calendar.JDateChooser();
        dateFin = new com.toedter.calendar.JDateChooser();
        jcbCategoria = new javax.swing.JComboBox();
        btnBuscarCultivar = new javax.swing.JButton();
        jcbTipo = new javax.swing.JComboBox();
        jtfPrecioTipo = new javax.swing.JTextField();
        jtfTotal = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtfCantidadTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescripcion = new javax.swing.JTextArea();
        lblCultivar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fecha inicio");

        jLabel2.setText("Fecha fin");

        jLabel3.setText("Categoria");

        jLabel4.setText("Tipo");

        jLabel5.setText("Cantidad tipo");

        jLabel6.setText("Precio tipo");

        jLabel7.setText("Total");

        jLabel8.setText("Descripción");

        jLabel9.setText("Cultivar");

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fumigar", "Labrar", "Podar", "Recolectar", "Regar", "Sembrar", "Otros" }));

        btnBuscarCultivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lupa.png"))); // NOI18N
        btnBuscarCultivar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarCultivarActionPerformed(evt);
            }
        });

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dias", "Horas" }));

        jtfPrecioTipo.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jtfPrecioTipoFocusLost(evt);
            }
        });

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        jtfCantidadTipo.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jtfCantidadTipoFocusLost(evt);
            }
        });

        jtaDescripcion.setColumns(20);
        jtaDescripcion.setRows(5);
        jtaDescripcion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtaDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtaDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfCantidadTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfPrecioTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCultivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48)
                        .addComponent(btnBuscarCultivar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(dateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfCantidadTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfPrecioTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarCultivar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCultivar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtfCantidadTipoFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtfCantidadTipoFocusLost
    {//GEN-HEADEREND:event_jtfCantidadTipoFocusLost
        if (!jtfCantidadTipo.getText().toString().equals("") && !jtfPrecioTipo.getText().toString().equals(""))
        {
            jtfTotal.setText(Float.parseFloat(jtfCantidadTipo.getText().toString()) * Float.parseFloat(jtfPrecioTipo.getText().toString()) + "");
        }
    }//GEN-LAST:event_jtfCantidadTipoFocusLost

    private void jtfPrecioTipoFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtfPrecioTipoFocusLost
    {//GEN-HEADEREND:event_jtfPrecioTipoFocusLost
        if (!jtfCantidadTipo.getText().toString().equals("") && !jtfPrecioTipo.getText().toString().equals(""))
        {
            jtfTotal.setText(Float.parseFloat(jtfCantidadTipo.getText().toString()) * Float.parseFloat(jtfPrecioTipo.getText().toString()) + "");
        }
    }//GEN-LAST:event_jtfPrecioTipoFocusLost

    private void jtaDescripcionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtaDescripcionKeyTyped
    {//GEN-HEADEREND:event_jtaDescripcionKeyTyped
        utils.UtilsTamanyo.maxTamanyo(jtaDescripcion, 300);
    }//GEN-LAST:event_jtaDescripcionKeyTyped

    private void btnBuscarCultivarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarCultivarActionPerformed
    {//GEN-HEADEREND:event_btnBuscarCultivarActionPerformed
        FrameSelecionarCultivar internal;
        try
        {
            internal = new FrameSelecionarCultivar(lblCultivar);
            internal.setVisible(true);
            utils.UtilsFrame.centrar(internal, 700, 400);
        } catch (Exception ex)
        {
            Logger.getLogger(NuevoGastoManoObra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarCultivarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        ConexionBBDD c = null;
        String fechaInicio = null, fechaFin = null;
        Date fInicio, fFin;
        String categoria;
        String tipo = null;
        float cantidadTipo, precioTipo, total;
        String descripcion;
        int idCultivar;
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");

        if (modificar)  // modificamos
        {
            try
            {
                fInicio = dateInicio.getDate();
                fFin = dateFin.getDate();
                //obtener variables, TODO agrupar en un método
                try
                {
                    fechaInicio = formatoFecha.format(dateInicio.getDate());
                    fechaFin = formatoFecha.format(dateFin.getDate());
                } catch (Exception ex)
                {
                    JOptionPane.showInternalMessageDialog(this.getContentPane(), "Debe selecionar las fechas");
                    Logger.getLogger(NuevoGastoManoObra.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                categoria = jcbCategoria.getSelectedItem().toString();
                cantidadTipo = Float.parseFloat(jtfCantidadTipo.getText().toString());
                precioTipo = Float.parseFloat(jtfPrecioTipo.getText().toString());
                total = Float.parseFloat(jtfTotal.getText().toString());
                descripcion = jtaDescripcion.getText().toString();
                idCultivar = Integer.parseInt(lblCultivar.getText().toString());
                tipo = jcbTipo.getSelectedItem().toString();

                if (fInicio.after(fFin))    //las fechas no están bien introdcidas
                {
                    JOptionPane.showInternalMessageDialog(jtbGastoManoObra.getRootPane(), "Debe selecionar las fechas correctas");
                } else
                {
                    String SQL = "UPDATE TGastosManoObra SET FechaInicio = \'" + fechaInicio
                            + "\', FechaFin =\'" + fechaFin + "\' ,Categoria = \"" + categoria + "\","
                            + " DNI = \"" + DNI + "\", Tipo =\"" + tipo + "\", CantidadTipo = \"" + cantidadTipo
                            + "\",PrecioTipo =\"" + precioTipo + "\",Total =\"" + total + "\",Descripcion =\"" + descripcion
                            + "\", IdCultivar = \"" + idCultivar
                            + "\" WHERE Id = \"" + id + "\";";

                    System.out.println(SQL);
                    c = new ConexionBBDD();
                    System.out.println(SQL);
                    c.hacerInsercion(SQL);
                    c.cerrarConexion();
                    this.dispose();
                }
                try
                {
                    jtbGastoManoObra = utils.UtilisSql.rellenarJTable("SELECT * FROM TGastosManoObra WHERE DNI = \"" + DNI + "\";", jtbGastoManoObra);
                } catch (SQLException ex)
                {
                    Logger.getLogger(NuevoGastoManoObra.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex)
                {
                    Logger.getLogger(NuevoGastoManoObra.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (ClassNotFoundException ex)
            {
                Logger.getLogger(NuevoGastoManoObra.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex)
            {
                Logger.getLogger(NuevoGastoManoObra.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else
        {
            try
            {   //obtener variables, TODO agrupar en un método
                fInicio = dateInicio.getDate();
                fFin = dateFin.getDate();
                try
                {
                    fechaInicio = formatoFecha.format(dateInicio.getDate());
                    fechaFin = formatoFecha.format(dateFin.getDate());
                } catch (Exception ex)
                {
                    JOptionPane.showInternalMessageDialog(this.getContentPane(), "Debe selecionar las fechas");
                    Logger.getLogger(NuevoGastoManoObra.class.getName()).log(Level.SEVERE, null, ex);
                }
                categoria = jcbCategoria.getSelectedItem().toString();
                cantidadTipo = Float.parseFloat(jtfCantidadTipo.getText().toString());
                precioTipo = Float.parseFloat(jtfPrecioTipo.getText().toString());
                total = Float.parseFloat(jtfTotal.getText().toString());
                descripcion = jtaDescripcion.getText().toString();
                idCultivar = Integer.parseInt(lblCultivar.getText().toString());
                tipo = jcbTipo.getSelectedItem().toString();

                if (fInicio.after(fFin))    //las fechas no están bien introdcidas
                {
                    JOptionPane.showInternalMessageDialog(this.getRootPane().getContentPane(), "Debe selecionar las fechas correctas");
                } else
                {
                    String SQL = "INSERT INTO TGastosManoObra (FechaInicio,FechaFin,Categoria,DNI,Tipo,CantidadTipo,PrecioTipo,Total,Descripcion,IdCultivar) \n"
                            + " VALUES (\'" + fechaInicio + "\',\'" + fechaFin
                            + "\',\"" + categoria + "\",\"" + DNI + "\",\"" + tipo
                            + "\",\"" + cantidadTipo + "\",\"" + precioTipo + "\",\""
                            + total + "\",\"" + descripcion + "\",\"" + idCultivar + "\");";
                    //System.out.println(SQL);
                    c = new ConexionBBDD();
                    System.out.println(SQL);
                    c.hacerInsercion(SQL);
                    c.cerrarConexion();
                    this.dispose();
                }
            } catch (Exception e)
            {
                JOptionPane.showInternalMessageDialog(this.getContentPane(), "Debe introducir todos los datos execto el id, use \'.\' para los decimales");
            }
            try
            {
                jtbGastoManoObra = utils.UtilisSql.rellenarJTable("SELECT * FROM TGastosManoObra WHERE DNI = \"" + DNI + "\";", jtbGastoManoObra);
            } catch (SQLException ex)
            {
                Logger.getLogger(NuevoGastoManoObra.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex)
            {
                Logger.getLogger(NuevoGastoManoObra.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(NuevoGastoManoObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(NuevoGastoManoObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(NuevoGastoManoObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(NuevoGastoManoObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new NuevoGastoManoObra().setVisible(true);
            }
        });
    }

    public void rellenarCampos() throws SQLException, Exception
    {
        try
        {
            ConexionBBDD c = new ConexionBBDD();
            String SQL = "SELECT * FROM TGastosManoObra WHERE Id = \"" + id + "\";";
            System.out.println(SQL);
            ResultSet rs = c.hacerConsulta(SQL);
            rs.next();

            dateInicio.setDate(rs.getDate("FechaInicio"));
            dateFin.setDate(rs.getDate("FechaFin"));
            jcbCategoria.getModel().setSelectedItem(rs.getString("Categoria"));
            jcbTipo.getModel().setSelectedItem(rs.getString("Tipo"));
            jtfCantidadTipo.setText(rs.getFloat("CantidadTipo") + "");
            jtfPrecioTipo.setText(rs.getFloat("PrecioTipo") + "");
            jtfTotal.setText(rs.getFloat("Total") + "");
            jtaDescripcion.setText(rs.getString("Descripcion"));
            lblCultivar.setText(rs.getString("IdCultivar"));
            c.cerrarConexion();

        } catch (ClassNotFoundException ex)
        {
            Logger.getLogger(InternalNuevaFinca.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCultivar;
    private com.toedter.calendar.JDateChooser dateFin;
    private com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbCategoria;
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JTextArea jtaDescripcion;
    private javax.swing.JTextField jtfCantidadTipo;
    private javax.swing.JTextField jtfPrecioTipo;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JLabel lblCultivar;
    // End of variables declaration//GEN-END:variables
}
