/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.internal.nuevo;

import conexion.ConexionBBDD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author david
 */
public class InternalNuevParcela extends javax.swing.JInternalFrame
{
    /*
     IdParcela       VARCHAR(20)     PRIMARY KEY,
     IdFinca         VARCHAR(20)     NOT NULL,
     Descripcion     VARCHAR(100)    NOT NULL,
     */

    javax.swing.JTable jtbParcela;
    String id;
    boolean modificar = false;

    /**
     * Creates new form InternalNuevParcela
     */
    public InternalNuevParcela(javax.swing.JTable jtbParcela)
    {
        initComponents();

        rellenarCombo();
        modificar = false;
        this.jtbParcela = jtbParcela;
        jtfIdParcela.setEditable(true);
    }

    public InternalNuevParcela(javax.swing.JTable jtbParcela, String id)
    {
        initComponents();
        modificar = false;
        this.jtbParcela = jtbParcela;
        this.id = id;
        System.out.println("this" + this.id);
        jtfIdParcela.setEditable(false);
        rellenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbFinca = new javax.swing.JComboBox();
        jtfIdParcela = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescripcionNuevo = new javax.swing.JTextArea();
        btnAceptarNueva = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setVisible(true);

        jLabel1.setText("Nombre");

        jLabel2.setText("Finca");

        jLabel3.setText("Descripción");

        jtaDescripcionNuevo.setColumns(20);
        jtaDescripcionNuevo.setLineWrap(true);
        jtaDescripcionNuevo.setRows(5);
        jScrollPane1.setViewportView(jtaDescripcionNuevo);

        btnAceptarNueva.setText("Aceptar");
        btnAceptarNueva.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarNuevaActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptarNueva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbFinca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jtfIdParcela))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfIdParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbFinca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarNueva)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAceptarNuevaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarNuevaActionPerformed
    {//GEN-HEADEREND:event_btnAceptarNuevaActionPerformed
        String NombreParcela = (String) jtfIdParcela.getText().toString();
        String Descripcion = (String) jtaDescripcionNuevo.getText().toString();
        String Finca = (String) jcbFinca.getSelectedItem();
        ConexionBBDD c = null;
        if (modificar)//modificar datos ==> distinto sql
        {
            try
            {
                c = new ConexionBBDD();
                String SQL = "UPDATE TParcela SET IdFinca = \"" + Finca
                        + "\", Descripcion =\"" + Descripcion
                        + "\" WHERE IdParcela = \"" + NombreParcela + "\";";
                c.hacerInsercion(SQL);
                c.cerrarConexion();
                jtbParcela = utils.Utilidades.rellenarJTable("SELECT * FROM TParcela;", jtbParcela);
            } catch (ClassNotFoundException ex)
            {
                Logger.getLogger(InternalNuevParcela.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex)
            {
                Logger.getLogger(InternalNuevParcela.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else
        {
            try
            {
                c = new ConexionBBDD();
                // String SQL = "INSERT INTO TParcela (IdParcela,IdFinca,Descripcion) VALUES (\""
                //         + NombreParcela + "\",\"" + Finca + "\",\"" + Descripcion + "\")";
                // System.out.println(SQL);
                c.hacerInsercion("INSERT INTO TParcela (IdParcela,IdFinca,Descripcion) VALUES (\""
                        + NombreParcela + "\",\"" + Finca + "\",\"" + Descripcion + "\")");
                c.cerrarConexion();
                jtbParcela = utils.Utilidades.rellenarJTable("SELECT * FROM TParcela;", jtbParcela);
            } catch (ClassNotFoundException ex)
            {
                Logger.getLogger(InternalNuevParcela.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex)
            {
                Logger.getLogger(InternalNuevParcela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dispose();
    }//GEN-LAST:event_btnAceptarNuevaActionPerformed

    void rellenarCampos()
    {
        try
        {
            rellenarCombo();
            System.out.println(id + "ssssssssssssss");
            ConexionBBDD c = new ConexionBBDD();
            String SQL = "SELECT * FROM TParcela WHERE IdParcela = \"" + id + "\";";
            System.out.println(SQL);
            ResultSet rs = c.hacerConsulta(SQL);
            rs.next();

            jtfIdParcela.setText(rs.getString("IdFinca") + "");
            jtaDescripcionNuevo.setText(rs.getString("Descripcion"));

            c.cerrarConexion();
        } catch (ClassNotFoundException ex)
        {
            Logger.getLogger(InternalNuevParcela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex)
        {
            Logger.getLogger(InternalNuevParcela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex)
        {
            Logger.getLogger(InternalNuevParcela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void rellenarCombo()
    {
        try
        {
            conexion.ConexionBBDD c = new ConexionBBDD();
            String SQL = "SELECT Nombre FROM TFinca";
            ResultSet rs = c.hacerConsulta(SQL);
            while (rs.next())
            {
                jcbFinca.addItem(rs.getString("Nombre"));
            }
            c.cerrarConexion();
        } catch (ClassNotFoundException ex)
        {
            Logger.getLogger(InternalNuevParcela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex)
        {
            Logger.getLogger(InternalNuevParcela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex)
        {
            Logger.getLogger(InternalNuevParcela.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarNueva;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbFinca;
    private javax.swing.JTextArea jtaDescripcionNuevo;
    private javax.swing.JTextField jtfIdParcela;
    // End of variables declaration//GEN-END:variables
}
