package gui.internal.nuevo;

import conexion.ConexionBBDD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author david
 */
public class InternalNuevoIngresoVenta extends javax.swing.JInternalFrame
{

    JTable jtable;
    int id;
    boolean modificar;

    public InternalNuevoIngresoVenta(JTable jtb)
    {
        try
        {
            initComponents();
            this.jtable = jtb;
            modificar = false;
            rellenarCombo();
        } catch (SQLException ex)
        {
            Logger.getLogger(InternalNuevoIngresoVenta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex)
        {
            Logger.getLogger(InternalNuevoIngresoVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public InternalNuevoIngresoVenta(JTable jtb, int id)
    {
        try
        {
            initComponents();
            this.jtable = jtb;
            modificar = true;
            this.id = id;
            rellenarCampos();
        } catch (Exception ex)
        {
            Logger.getLogger(InternalNuevoIngresoVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        dateIngreso = new com.toedter.calendar.JDateChooser();
        jtfCliente = new javax.swing.JTextField();
        jcbCultivar = new javax.swing.JComboBox();
        jtfPrecioUnidad = new javax.swing.JTextField();
        jtfCantidad = new javax.swing.JTextField();
        jtfTotal = new javax.swing.JTextField();

        setVisible(true);

        jLabel1.setText("Identificador");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha");

        jLabel3.setText("Cliente");

        jLabel4.setText("Precio unidad");

        jLabel5.setText("Cantidad");

        jLabel6.setText("Total");

        jLabel7.setText("Cultivar");

        jtfId.setEditable(false);

        jcbCultivar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbCultivarActionPerformed(evt);
            }
        });

        jtfPrecioUnidad.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jtfPrecioUnidadFocusLost(evt);
            }
        });

        jtfCantidad.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jtfCantidadFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfId)
                            .addComponent(jtfCliente)
                            .addComponent(jtfPrecioUnidad)
                            .addComponent(jtfCantidad)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(103, 103, 103))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addGap(98, 98, 98)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfTotal)
                            .addComponent(jcbCultivar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dateIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtfPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jcbCultivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbCultivarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbCultivarActionPerformed
    {//GEN-HEADEREND:event_jcbCultivarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCultivarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        ConexionBBDD c = null;
        String fecha = null, nombre = null;
        float precioUnidad = 0, cantidad = 0, total = 0;
        int idCultivar = 0;
        if (modificar) //se modifican datos
        {

            try
            {
                c = new ConexionBBDD();
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                fecha = formatoFecha.format(dateIngreso.getDate());
                nombre = jtfCliente.getText().toString();
                precioUnidad = Float.parseFloat(jtfPrecioUnidad.getText().toString());
                cantidad = Float.parseFloat(jtfCantidad.getText().toString());
                if (!jtfPrecioUnidad.getText().toString().equals("") && !jtfCantidad.getText().toString().equals(""))
                {
                    total = precioUnidad * cantidad;
                } else
                {
                    total = Float.parseFloat(jtfTotal.getText().toString());
                }
                idCultivar = Integer.parseInt(jcbCultivar.getSelectedItem().toString());
                String SQL = "UPDATE TIngresoVenta SET Fecha = \'" + fecha
                        + "\', NombreCliente = \"" + nombre + "\", PrecioUnidad = \""
                        + precioUnidad + "\", Cantidad = \"" + cantidad + "\", Total = \""
                        + total + "\", IdCultivar = \"" + idCultivar + "\" WHERE Id = \"" + id + "\";";
                System.out.println(SQL);
                c.hacerInsercion(SQL);
                c.cerrarConexion();
                dispose();
                utils.UtilisSql.actualizarJtable(jtable, "TIngresoVenta");
            } catch (Exception ex)
            {
                JOptionPane.showInternalMessageDialog(jtable.getRootPane(), "Debe introducir todos los datos, use \'.\' para los decimales");
                Logger.getLogger(InternalNuevoIngresoVenta.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else// nueva alta
        {

            try
            {
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                fecha = formatoFecha.format(dateIngreso.getDate());
                nombre = jtfCliente.getText().toString();
                precioUnidad = Float.parseFloat(jtfPrecioUnidad.getText().toString());
                cantidad = Float.parseFloat(jtfCantidad.getText().toString());
                if (!jtfPrecioUnidad.getText().toString().equals("") && !jtfCantidad.getText().toString().equals(""))
                {
                    total = precioUnidad * cantidad;
                } else
                {
                    total = Float.parseFloat(jtfTotal.getText().toString());
                }
                idCultivar = Integer.parseInt(jcbCultivar.getSelectedItem().toString());
            } catch (Exception ex)
            {
                JOptionPane.showInternalMessageDialog(jtable.getRootPane(), "Debe introducir todos los datos, use \'.\' para los decimales");
            }
            String SQL = "INSERT INTO TIngresoVenta (Fecha,NombreCliente,PrecioUnidad,Cantidad,Total,IdCultivar) \n"
                    + "    VALUES (\'" + fecha + "\',\"" + nombre + "\",\""
                    + precioUnidad + "\",\"" + cantidad + "\",\"" + total + "\",\""
                    + idCultivar + "\");";
            System.out.println(SQL);
            try
            {
                c = new ConexionBBDD();
                c.hacerInsercion(SQL);
                c.cerrarConexion();
                dispose();
                utils.UtilisSql.actualizarJtable(jtable, "TIngresoVenta");
            } catch (ClassNotFoundException ex)
            {
                Logger.getLogger(InternalNuevoIngresoVenta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex)
            {
                Logger.getLogger(InternalNuevoIngresoVenta.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jtfCantidadFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtfCantidadFocusLost
    {//GEN-HEADEREND:event_jtfCantidadFocusLost
        if (!jtfPrecioUnidad.getText().toString().equals("") && !jtfCantidad.getText().toString().equals(""))
        {
            jtfTotal.setText(Float.parseFloat(jtfPrecioUnidad.getText().toString()) * Float.parseFloat(jtfCantidad.getText().toString()) + "");
        }
    }//GEN-LAST:event_jtfCantidadFocusLost

    private void jtfPrecioUnidadFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jtfPrecioUnidadFocusLost
    {//GEN-HEADEREND:event_jtfPrecioUnidadFocusLost
        if (!jtfPrecioUnidad.getText().toString().equals("") && !jtfCantidad.getText().toString().equals(""))
        {
            jtfTotal.setText(Float.parseFloat(jtfPrecioUnidad.getText().toString()) * Float.parseFloat(jtfCantidad.getText().toString()) + "");
        }
    }//GEN-LAST:event_jtfPrecioUnidadFocusLost
    void rellenarCombo() throws ClassNotFoundException, SQLException, Exception
    {
        ConexionBBDD c = new ConexionBBDD();
        String SQL = "SELECT Id FROM TCultivar ORDER BY 1;";
        ResultSet rs = c.hacerConsulta(SQL);
        while (rs.next())
        {
            jcbCultivar.addItem(rs.getString(1));
        }
        c.cerrarConexion();
    }

    void rellenarCampos()
    {
        try
        {
            rellenarCombo();
            ConexionBBDD c = new ConexionBBDD();
            String SQL = "SELECT * FROM TIngresoVenta WHERE Id = \"" + id + "\";";
            ResultSet rs = c.hacerConsulta(SQL);
            rs.next();

            jtfId.setText(rs.getInt("Id") + "");
            dateIngreso.setDate(rs.getDate("Fecha"));
            jtfCliente.setText(rs.getString("NombreCliente"));
            jtfPrecioUnidad.setText(rs.getFloat("PrecioUnidad") + "");
            jtfCantidad.setText(rs.getFloat("Cantidad") + "");
            jtfTotal.setText(rs.getFloat("Total") + "");
        } catch (SQLException ex)
        {
            Logger.getLogger(InternalNuevoIngresoVenta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex)
        {
            Logger.getLogger(InternalNuevoIngresoVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private com.toedter.calendar.JDateChooser dateIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbCultivar;
    private javax.swing.JTextField jtfCantidad;
    private javax.swing.JTextField jtfCliente;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfPrecioUnidad;
    private javax.swing.JTextField jtfTotal;
    // End of variables declaration//GEN-END:variables
}
